# Bioinformatics Project - Computational Drug Discovery [Part 1] Download Bioactivity Data (Concised version)
Chanin Nantasenamat

'Data Professor' YouTube channel http://youtube.com/dataprofessor

In this Jupyter notebook, we will be building a real-life data science project that you can include in your data science portfolio. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In Part 1, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

Note for this Concised Version:

Redundant code cells were deleted.
Code cells for saving files to Google Drive has been deleted.

## ChEMBL Database
The ChEMBL Database is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications. [Data as of March 25, 2020; ChEMBL version 26].

## Installing Libraries

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [4]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (0.10.9)
Requirement already satisfied: urllib3 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from chembl_webresource_client) (2.7.0)
Requirement already satisfied: requests>=2.18.4 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from chembl_webresource_client) (2.34.2)
Requirement already satisfied: requests-cache~=1.2 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.3)
Requirement already satisfied: url-normalize>=2.0 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.5.0)
Requirement already satisfied: idna<4,>=2.5 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)

## import libraries

In [7]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

## Search for target protein

In [11]:
target = new_client.target
target_query = target.search('acetylcholinesterase')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Drosophila melanogaster,Acetylcholinesterase,18.0,False,CHEMBL2242744,"[{'accession': 'P07140', 'component_descriptio...",SINGLE PROTEIN,7227
1,[],Homo sapiens,Acetylcholinesterase,16.0,False,CHEMBL220,"[{'accession': 'P22303', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Torpedo californica,Acetylcholinesterase,16.0,False,CHEMBL4780,"[{'accession': 'P04058', 'component_descriptio...",SINGLE PROTEIN,7787
3,[],Mus musculus,Acetylcholinesterase,16.0,False,CHEMBL3198,"[{'accession': 'P21836', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Rattus norvegicus,Acetylcholinesterase,16.0,False,CHEMBL3199,"[{'accession': 'P37136', 'component_descriptio...",SINGLE PROTEIN,10116
5,[],Electrophorus electricus,Acetylcholinesterase,16.0,False,CHEMBL4078,"[{'accession': 'O42275', 'component_descriptio...",SINGLE PROTEIN,8005
6,[],Bos taurus,Acetylcholinesterase,16.0,False,CHEMBL4768,"[{'accession': 'P23795', 'component_descriptio...",SINGLE PROTEIN,9913
7,[],Anopheles gambiae,Acetylcholinesterase,16.0,False,CHEMBL2046266,"[{'accession': 'Q869C3', 'component_descriptio...",SINGLE PROTEIN,7165
8,[],Bemisia tabaci,AChE2,16.0,False,CHEMBL2366409,"[{'accession': 'B3SST5', 'component_descriptio...",SINGLE PROTEIN,7038
9,[],Leptinotarsa decemlineata,Acetylcholinesterase,16.0,False,CHEMBL2366490,"[{'accession': 'Q27677', 'component_descriptio...",SINGLE PROTEIN,7539
10,[],Nephotettix cincticeps,Ace-orthologous acetylcholinesterase,16.0,False,CHEMBL2366514,"[{'accession': 'Q9NJH6', 'component_descriptio...",SINGLE PROTEIN,94400
11,[],Gallus gallus,Acetylcholinesterase,16.0,False,CHEMBL3227914,"[{'accession': 'P36196', 'component_descriptio...",SINGLE PROTEIN,9031
12,[],Danio rerio,Acetylcholinesterase,16.0,False,CHEMBL3308995,"[{'accession': 'Q9DDE3', 'component_descriptio...",SINGLE PROTEIN,7955
13,[],Aedes aegypti,Acetylcholinesterase,16.0,False,CHEMBL4295607,"[{'accession': 'Q6A2E2', 'component_descriptio...",SINGLE PROTEIN,7159
14,[],Homo sapiens,Protein CutA,16.0,False,CHEMBL6067022,"[{'accession': 'O60888', 'component_descriptio...",SINGLE PROTEIN,9606
15,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL5752,"[{'accession': 'Q95P20', 'component_descriptio...",SINGLE PROTEIN,7370
16,[],Plutella xylostella,Acetylcholinesterase,15.0,False,CHEMBL2242729,"[{'accession': 'Q8MZM0', 'component_descriptio...",SINGLE PROTEIN,51655
17,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL2242743,"[{'accession': 'Q7YWJ9', 'component_descriptio...",SINGLE PROTEIN,7370
18,[],Pediculus humanus capitis,Acetylcholinesterase,15.0,False,CHEMBL2362988,"[{'accession': 'A2PZ98', 'component_descriptio...",SINGLE PROTEIN,121226
19,[],Spodoptera litura,Acetylcholinesterase,15.0,False,CHEMBL2366422,"[{'accession': 'C5IU80', 'component_descriptio...",SINGLE PROTEIN,69820
20,[],Laodelphax striatella,Acetylcholinesterase,15.0,False,CHEMBL2366446,"[{'accession': 'K4JQ36', 'component_descriptio...",SINGLE PROTEIN,195883
21,[],Schizaphis graminum,Acetylcholinesterase,15.0,False,CHEMBL2366511,"[{'accession': 'Q9BMJ1', 'component_descriptio...",SINGLE PROTEIN,13262
22,[],Homo sapiens,Cholinesterases; ACHE & BCHE,14.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606
23,[],Rattus norvegicus,Acetylcholinesterase and butyrylcholinesterase...,14.0,False,CHEMBL2111475,"[{'accession': 'P37136', 'component_descriptio...",SELECTIVITY GROUP,10116
24,[],Caenorhabditis elegans,Acetylcholinesterase 1,14.0,False,CHEMBL3341583,"[{'accession': 'P38433', 'component_descriptio...",SINGLE PROTEIN,6239
25,[],Equus caballus,Butyrylcholinesterase,11.0,False,CHEMBL5077,"[{'accession': 'Q9N1N9', 'component_descriptio...",SINGLE PROTEIN,9796
26,[],Equus caballus,Cholinesterase,11.0,False,CHEMBL5763,"[{'accession': 'P81908', 'component_descriptio...",SINGLE PROTEIN,9796
27,[],Canis lupus familiaris,Cholinesterase,11.0,False,CHEMBL4630814,"[{'accession': 'P32750', 'component_descriptio...",SINGLE PROTEIN,9615
28,[],Mus musculus,Cholinesterase,10.0,False,CHEMBL2528,"[{'accession': 'Q03311', 'component_descriptio...",SINGLE PROTEIN,10090
29,[],Rattus norvegicus,Butyrylcholinesterase,10.0,False,CHEMBL3403,"[{'accession': 'Q9JKC1', 'component_descriptio...",SINGLE PROTEIN,10116
30,[],Homo sapiens,Cholinesterase,5.0,False,CHEMBL1914,"[{'accession': 'P06276', 'component_descriptio...",SINGLE PROTEIN,9606

## Select and retrieve bioactivity data for _Human Acetylcholinesterase_ (second entry in the previous dataframe)

We will assign the second entry [1] (which corresponds to the target protein, Human Acetylcholinesterase) to the selected_target variable

In [12]:
selected_target = targets.target_chembl_id[1]
selected_target

'CHEMBL220'

We will retrieve only bioactivity data for _Human Acetylcholinesterase_ (CHEMBL220) that are reported as pChEMBL values.

In [13]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [14]:
df = pd.DataFrame.from_dict(res)

In [15]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,NaN,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.75
1,None,NaN,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.1
2,None,NaN,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,50.0
3,None,NaN,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.3
4,None,NaN,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10074,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29307984,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.4
10075,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29307985,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,2.16
10076,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309041,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,11.1
10077,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309042,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.052
10078,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309043,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,2.61

Save the resulting bioactivity data to a CSV file **bioactivity_data.csv**

In [8]:
df.to_csv('acetylcholinesterase_01_bioactivity_data_raw.csv', index=False)

## Handling missing data

If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [16]:
df2 = df[df.standard_value.notna()]
df2  = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_68/3354437670.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2  = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,NaN,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.75
1,None,NaN,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.1
2,None,NaN,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,50.0
3,None,NaN,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.3
4,None,NaN,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10074,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29307984,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.4
10075,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29307985,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,2.16
10076,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309041,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,11.1
10077,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309042,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.052
10078,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309043,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,2.61

In [17]:
len(df2.canonical_smiles.unique())

7175

In [18]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,NaN,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.75
1,None,NaN,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.1
2,None,NaN,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,50.0
3,None,NaN,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.3
4,None,NaN,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10073,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29307981,[],CHEMBL6183007,Inhibition of AChE (unknown origin) using acet...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,0.48
10074,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29307984,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.4
10076,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309041,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,11.1
10077,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309042,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,uM,UO_0000065,NaN,0.052
10078,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,29309043,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,NaN,None,IC50,nM,UO_0000065,NaN,2.61

## Data pre-processing of the bioactivity data

### Combining 3 relevant columns (molecule_chembl_id, canonical_smiles, standard_value) and bioactivty_class into a DataFrame

In [19]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.0
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.0
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.0
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.0
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.0
...,...,...,...
10073,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,0.48
10074,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,400.0
10076,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,11.1
10077,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,52.0
10078,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,2.61

Save dataframe to CSV file

In [13]:
df3.to_csv('acetylcholinesterase_02_bioactivity_data_preprocessed.csv', index=False)

## Labeling compounds: Active, Inactive or Intermediate

The bioactivity data is in the IC50 unit. Compounds having values of less than 1000nM will be considered to be **active** while those greater than 10000 nM will be considered to be **inactive**. As for those values in between 1000 and 10000 nM will be referred to as **intermediate**.

In [20]:
df4 = pd.read_csv('acetylcholinesterase_02_bioactivity_data_preprocessed.csv')

In [21]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [22]:
bioactivity_class = pd.Series(bioactivity_threshold, name='bioactivity_class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.00,active
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.00,active
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.00,inactive
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.00,active
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.00,active
...,...,...,...,...
7170,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,0.48,active
7171,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,400.00,active
7172,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,11.10,active
7173,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,52.00,active
7174,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,2.61,active

In [23]:
df5.to_csv('acetylcholinesterase_03_bioactivity_data_curated.csv', index=False)

In [ ]:
! sudo apt-get update
! sudo apt-get install zip

In [19]:
! zip acetylcholinesterase.zip *.csv

/bin/bash: zip: command not found